# Generated by Django 4.0.4 on 2022-04-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inFlow', models.PositiveIntegerField()),
                ('outFlow', models.PositiveIntegerField()),
                ('balanceFlow', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
