# Generated by Django 4.0.4 on 2022-04-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='balanceFlow',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='date',
        ),
    ]
