# Generated by Django 4.0.4 on 2022-04-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_apis', '0002_remove_budget_balanceflow_remove_budget_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='balanceFlow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
