# Generated by Django 4.0.4 on 2022-04-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_apis', '0003_budget_balanceflow_budget_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
